baseURL = "https://example.org/"
defaultContentLanguage = "fr"
enableRobotsTXT = true
languageCode = "en"
theme = "gokarna"
title = "Mon portfolio"
  

[params]
  avatarAltText = "avatar"
  avatarSize = "size-m"
  avatarURL = "/img/pp.png"

  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """

  description = "Bonjour ! Je suis Clémentin GRANIER, étudiant en Génie Électrique à l'INSA Lyon et passionné d'électronique."
  footer = "The Marauders"
  metaKeywords = ["blog", "gokarna", "hugo"]
  showBackToTopButton = true

  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/cl%C3%A9mentin-granier-2386b9183/"},
    {name = "github", url = "https://github.com/Whitebowfr"},
    {name = "email", url = "mailto:clementin.granier@insa-lyon.fr"}
  ]

[menu]
  [[menu.main]]
    name = "Accueil"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Informatique"
    pre = "<span data-feather='code'></span>"
    url = "/informatique/"
    weight = 2

  [[menu.main]]
    name = "Électronique"
    pre = "<span data-feather='zap'></span>"
    url = "/electronique/"
    weight = 3

  [[menu.main]]
    name = "Autres"
    pre = "<span data-feather='box'></span>"
    url = "/autres/"
    weight = 4

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
  [markup.goldmark.renderer]
    unsafe=true

[minify]
    minifyOutput = true